---
title: "Exercise_Single_Var"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE)
```


## 1.钻石
```{r}
library(ggplot2)
data(diamonds)

summary(diamonds)

?diamonds
names(diamonds)
```

## 2&3 价格直方图
```{r}
qplot(x = price, data = diamonds)
summary(diamonds$price)
```

## 4.钻石数量

```{r}
# How many diamonds cost less than $500?
subset(diamonds, price < 500)

# How many diamonds cost less than $250?
subset(diamonds, price < 250)

# How many diamonds cost $15000 or more?
subset(diamonds, price >= 15000)
```

## 5.廉价钻石
```{r}
qplot(x = price, data = diamonds, binwidth = 1) +
  scale_x_continuous(limits = c(200,2000),breaks = seq(200,2000,200))

# There are no diamonds that cost $1500, For diamonds that cost less than $2000,the most price of a diamend is 
# around $700 with the mode being $605. The second insight comes from Paula F.
```

## 6&7.切工-价格
```{r}
# Break out the histogram of diamond price by cut 

qplot(x = price, data = diamonds, binwidth = 1) +
  scale_x_continuous(limits = c(200,2000),breaks = seq(200,2000,500)) + 
  facet_wrap(~cut)

by(diamonds$price,diamonds$cut,summary)

```

## 8.标尺和多直方图
```{r}
# In the two last exercises,we look at the distribution for diamonds by cut
# Run the code below in R to generate the histogram as a reminder

qplot(x = price,data = diamonds) +
  facet_wrap(~cut)

# Modifying facet label appearance

sp <- ggplot(diamonds,aes(x = price)) +
  geom_histogram()
sp + facet_wrap(~cut) + 
  theme(strip.text.x = element_text(size = 8,angle = 75),
        strip.text.y = element_text(size = 12,face = "bold"),
        strip.background = element_rect(colour = "red",fill = "#CCCCFF"))

# Free Scales
sp + facet_wrap(~cut,scales = "free")

```

## 9.由切工决定的每克拉价格
```{r}
# Create a histogram of price per carat and facet it by cut.
# You can make adjustments to the code from previous exercise to get started

price_by_carat <- ggplot(diamonds,aes(x = price/carat)) +
  geom_histogram()



# Adjust the bin width and trancform the scale of x-axis using log10
price_by_carat + scale_x_log10()

# (If the Very Good facet looks smooth, try decreasing your bin width! If the data looks skewed, did you remember to perform a log10 transform?)

```

## 10.价格箱线图
```{r}
# Investigate the price of diamends using box plots, numerical summeries, and one of the 
# following categorical variables:cut,clarity,or color.

price_in_cut <- ggplot(diamonds,aes(x = cut, y = price)) +
  geom_boxplot() +
  coord_cartesian(ylim = c(0,7000))
price_in_cut

price_in_clarity <- ggplot(diamonds,aes(x = clarity, y = price)) +
  geom_boxplot() +
  coord_cartesian(ylim = c(0,7000))
price_in_clarity

price_in_color <- ggplot(diamonds,aes(x = color, y = price)) +
  geom_boxplot() +
  coord_cartesian(ylim = c(0,8000))
price_in_color

# Numerous summeries
by(diamonds$price,diamonds$color,summary)
by(diamonds$price,diamonds$clarity,summary)

# IQR
IQR(subset(diamonds,color=="J")$price)

```

## 12.由颜色标识的每克拉价格箱线图
```{r}
# Investigate the price per carat of diamends across
# the different colors of diamends using boxplots.

price_in_color_carat <- ggplot(diamonds,aes(x = color, y = price/carat)) +
  geom_boxplot() +
  coord_cartesian(ylim = c(0,6000))

price_in_color_carat
```

## 13. 克拉频率多边形
```{r}
# Investigate the weight of the diamends(carat) using a frequency polygon
ggplot(diamonds,aes(x = carat)) +
  geom_freqpoly(binwidth=0.1) +
  scale_x_continuous(breaks = seq(0,5,0.2)) +
  scale_y_continuous(breaks = seq(0,12000,2000))


```

## 15.Gapminder 数据
```{r}
# The Gapminder website contains over 500 data sets with information about
# the world's population. Download a data set of your choice and create 2-5 plots that
# make use of the techniques from lesson 3.
library(ggplot2)
library(tidyr)
library(dplyr)

data = read.csv("gdp_per_capita_ppp.csv")

summary(data)
```



